apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  namespace: development
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: database
    app.kubernetes.io/owner: retail-store-sample
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Y2F0YWxvZ19wYXNz
  RETAIL_CATALOG_PERSISTENCE_USER: Y2F0YWxvZ191c2Vy
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: Y2F0YWxvZ19wYXNz
