apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-db
  namespace: development
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: ap-southeast-1
    objects: |
      - objectName: "retail-store/catalog/db2"
        objectType: "secretsmanager"
        jmesPath:
          - path: MYSQL_ROOT_PASSWORD
            objectAlias: MYSQL_ROOT_PASSWORD
          - path: RETAIL_CATALOG_PERSISTENCE_USER
            objectAlias: RETAIL_CATALOG_PERSISTENCE_USER
          - path: RETAIL_CATALOG_PERSISTENCE_PASSWORD
            objectAlias: RETAIL_CATALOG_PERSISTENCE_PASSWORD
  secretObjects:
    - secretName: catalog-db
      type: Opaque
      data:
        - objectName: MYSQL_ROOT_PASSWORD
          key: MYSQL_ROOT_PASSWORD
        - objectName: RETAIL_CATALOG_PERSISTENCE_USER
          key: RETAIL_CATALOG_PERSISTENCE_USER
        - objectName: RETAIL_CATALOG_PERSISTENCE_PASSWORD
          key: RETAIL_CATALOG_PERSISTENCE_PASSWORD
