apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: development
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/owner: retail-store-sample
