apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
  labels:
    app.kubernetes.io/owner: retail-store-sample
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
