apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: development
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/owner: retail-store-sample
data:
  RETAIL_UI_THEME: default
  RETAIL_UI_SEARCH_ENABLED: "false"
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog
