apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-production
  namespace: argocd
  labels:
    app.kubernetes.io/owner: retail-store-sample
    app.kubernetes.io/component: application
spec:
  project: default
  source:
    repoURL: https://github.com/Son514/retail-store-app.git
    targetRevision: main
    path: k8s/charts/catalog
    helm:
      releaseName: catalog
      valueFiles:
        - ../../envs/production/catalog-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false