apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-app
  namespace: development
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: ap-southeast-1
    objects: |
      - objectName: "retail-store/catalog/db2"
        objectType: "secretsmanager"
        jmesPath:
          - path: RETAIL_CATALOG_PERSISTENCE_USER
            objectAlias: RETAIL_CATALOG_PERSISTENCE_USER
          - path: RETAIL_CATALOG_PERSISTENCE_PASSWORD
            objectAlias: RETAIL_CATALOG_PERSISTENCE_PASSWORD
